nodeLinker: node-modules

packageExtensions:
  "@nuxt/devtools@*":
    peerDependencies:
      vue: "*"
  "@nuxt/eslint-config@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      typescript: "*"
  "@nuxt/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  "@nuxt/eslint@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      typescript: "*"
      vite: "*"
  "@nuxtjs/stylelint-module@*":
    dependencies:
      vite: "^7.0.0"
      webpack: "^5.0.0"
  "nuxt-viewport@*":
    peerDependencies:
      vue: "*"
  "nuxt@*":
    peerDependencies:
      vite: "*"
